import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { FORMAT_ARGS, lockedVersion } from '../check-application-format.mjs';
import { guidanceDrift, guidanceHashes } from '../template-guidance.mjs';

const root = path.resolve(import.meta.dirname, '../../..');
const read = (file) => readFileSync(path.join(root, file), 'utf8');

test('application guidance is exactly what the template generated', () => {
  assert.deepEqual(
    guidanceDrift(root),
    [],
    'A refresh replaces AGENTS.md and CLAUDE.md; put factory guidance in .github/AGENTS.md',
  );
});

test('factory maintainer guidance lives under .github, where it survives a refresh', () => {
  assert.match(
    read('.github/AGENTS.md'),
    /^## Template-owned application files$/m,
  );
  assert.equal(read('.github/CLAUDE.md'), '@AGENTS.md\n');
  assert.doesNotMatch(
    read('AGENTS.md'),
    /^## (?:Factory|Controlled failed-delivery|Ordinary preset)/m,
  );
});

test('drift names an edited, missing or unrecorded guidance file', (t) => {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'template-guidance-'));
  t.after(() => rmSync(dir, { recursive: true, force: true }));
  const write = (file, text) => writeFileSync(path.join(dir, file), text);
  write('AGENTS.md', '# Guide\n');
  write('CLAUDE.md', '@AGENTS.md\n');
  write(
    'factory-template.json',
    JSON.stringify({ guidance: guidanceHashes(dir) }),
  );
  assert.deepEqual(guidanceDrift(dir), []);
  write('AGENTS.md', '# Guide\n\n\n## Factory notes\n');
  assert.deepEqual(guidanceDrift(dir), [
    "AGENTS.md differs from the template's version",
  ]);
  rmSync(path.join(dir, 'CLAUDE.md'));
  assert.ok(guidanceDrift(dir).includes('CLAUDE.md is missing'));
  write('factory-template.json', JSON.stringify({ guidance: {} }));
  assert.ok(
    guidanceDrift(dir).includes('AGENTS.md was not generated by the template'),
  );
  write('factory-template.json', '{}');
  assert.deepEqual(guidanceDrift(dir), [
    'factory-template.json records no template guidance hashes',
  ]);
});

test('the factory format check runs what build verification runs, with the pinned tools', () => {
  assert.match(
    read('.github/scripts/verify.sh'),
    /pnpm format:check '!\.github\/\*\*'/,
  );
  assert.equal(
    JSON.parse(read('package.json')).scripts['format:check'],
    'prettier . --check',
  );
  assert.deepEqual(FORMAT_ARGS, ['.', '--check', '!.github/**']);
  const lockfile = read('pnpm-lock.yaml');
  assert.match(lockedVersion(lockfile, 'prettier'), /^\d+\.\d+\.\d+$/);
  assert.match(
    lockedVersion(lockfile, '@nocobase/dev-config'),
    /^\d+\.\d+\.\d+/,
  );
  const workflow = read('.github/workflows/factory-tests.yml');
  assert.match(
    workflow,
    /node \.github\/scripts\/check-application-format\.mjs/,
  );
  // The format check covers the whole application root, so no path filter
  // may exclude a pull request from it: one touching only client/ or server/
  // would otherwise reach a build task with a formatting defect.
  const triggers = workflow.split('\non:\n')[1].split('\npermissions:')[0];
  assert.doesNotMatch(triggers, /paths(?:-ignore)?:/);
  assert.match(
    triggers,
    /^  pull_request:\n  push:\n    branches: \[develop\]\n/m,
  );
});

test('lockedVersion reads the root importer and drops peer suffixes', () => {
  const lockfile = `lockfileVersion: '9.0'

importers:

  .:
    devDependencies:
      '@nocobase/dev-config':
        specifier: 0.1.0-beta.13
        version: 0.1.0-beta.13(9e5d7b4f)
      prettier:
        specifier: ^3.9.6
        version: 3.9.9

  packages/other:
    devDependencies:
      eslint:
        specifier: ^9
        version: 9.0.0

packages:
`;
  assert.equal(lockedVersion(lockfile, 'prettier'), '3.9.9');
  assert.equal(
    lockedVersion(lockfile, '@nocobase/dev-config'),
    '0.1.0-beta.13',
  );
  assert.throws(() => lockedVersion(lockfile, 'eslint'), /does not pin eslint/);
});
