/** Views the after-sales service domain returns to its pages. */

export interface MemberView {
  id: number | null;
  ref: string | null;
  name: string | null;
  kind: string | null;
  email: string | null;
  groupId: number | null;
  groupName: string | null;
  userId: string | null;
  enabled: boolean | null;
  openWorkOrders?: number;
}

export interface CustomerView {
  id: number | null;
  name: string | null;
  contactName: string | null;
  contactPhone: string | null;
  address: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}

export interface EquipmentView {
  id: number | null;
  code: string | null;
  name: string | null;
  model: string | null;
  location: string | null;
  enabled: boolean | null;
  nextInspectionDate: string | null;
  customerId: number | null;
  customer: { id: number | null; name: string | null } | null;
  engineerMemberId: number | null;
  serviceEngineer: MemberView | null;
  note: string | null;
}

export interface AttachmentView {
  id: string;
  filename: string;
  ext: string | null;
  mimeType: string | null;
  size: number;
  category: 'photo' | 'report';
  createdAt: string | null;
  contentUrl: string;
}

export interface ShareView {
  id: number | null;
  engineerMemberId: number | null;
  engineer: MemberView | null;
  grantedAt: string | null;
  revokedAt: string | null;
  note: string | null;
}

export interface WorkOrderEventView {
  id: number | null;
  type: string | null;
  message: string | null;
  actorId: string | null;
  runId: string | null;
  createdAt: string | null;
}

export interface WorkOrderCapabilities {
  canAccept: boolean;
  canRetryAcceptance: boolean;
  canStart: boolean;
  canSubmitResolution: boolean;
  canClose: boolean;
  canReject: boolean;
  canShare: boolean;
  canUploadAttachment: boolean;
  canViewInternalNotes: boolean;
  canEditCatalog: boolean;
  canMaintainKnowledge: boolean;
  canMaintainManuals: boolean;
  canManageShares: boolean;
  canManageInspections: boolean;
}

export interface WorkOrderView {
  id: number | null;
  orderNo: string | null;
  title: string | null;
  problem: string | null;
  priority: string | null;
  status: string | null;
  source: string | null;
  confidential: boolean | null;
  deadline: string | null;
  createdAt: string | null;
  updatedAt: string | null;
  acceptedAt: string | null;
  processingStartedAt: string | null;
  resolutionAt: string | null;
  closedAt: string | null;
  acceptNoteStatus: string | null;
  acceptanceNote: string | null;
  resolution: string | null;
  lastRejectReason: string | null;
  rejectCount: number | null;
  customerId: number | null;
  customer: {
    id: number | null;
    name: string | null;
    contactName?: string | null;
    contactPhone?: string | null;
    address?: string | null;
  } | null;
  equipmentId: number | null;
  equipment: {
    id: number | null;
    code: string | null;
    name: string | null;
    model: string | null;
    location?: string | null;
    nextInspectionDate?: string | null;
  } | null;
  assignee: MemberView | null;
  capabilities: WorkOrderCapabilities;
  createdById?: string | null;
  acceptanceRunId?: string | null;
  events?: WorkOrderEventView[];
  attachments?: AttachmentView[];
  shares?: ShareView[];
}

export interface InspectionView {
  id: number | null;
  taskNo: string | null;
  status: string | null;
  planDate: string | null;
  dueAt: string | null;
  completedAt: string | null;
  result: string | null;
  autoGenerated: boolean;
  equipment: {
    id: number | null;
    code: string | null;
    name: string | null;
  } | null;
  customer: { id: number | null; name: string | null } | null;
  engineer: MemberView | null;
}

export interface KnowledgeView {
  id: number | null;
  title: string | null;
  body: string | null;
  published: boolean | null;
  createdAt: string | null;
  updatedAt: string | null;
}

export interface ManualView {
  id: number | null;
  title: string | null;
  equipmentModel: string | null;
  summary: string | null;
  sourceFileId: string | null;
  sourceFile: {
    id: string;
    filename: string | null;
    ext: string | null;
    mimeType: string | null;
    size: number | null;
  } | null;
  indexStatus: string | null;
  indexMessage: string | null;
  indexedAt: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}

export interface ExternalEventView {
  id: number | null;
  eventId: string | null;
  source: string | null;
  status: string | null;
  message: string | null;
  workOrderId: number | null;
  createdAt: string | null;
  updatedAt: string | null;
}

export interface DashboardView {
  scope: string | null;
  generatedAt: string | null;
  totals: {
    total: number;
    open: number;
    overdue: number;
    urgent: number;
    pendingAcceptance: number;
    pendingConfirmation: number;
  };
  statuses: { status: string; count: number }[];
  groups: {
    id: number;
    name: string | null;
    total: number;
    open: number;
    engineers: {
      id: number;
      ref: string | null;
      name: string | null;
      groupName: string | null;
      total: number;
      open: number;
    }[];
  }[];
  mine: { total: number; open: number } | null;
}

export interface IntegrationView {
  externalSource: string | null;
  knowledgeIndexConfigured: boolean;
  notificationConfigured: boolean;
  workflowConfigured: boolean;
  eventStatuses: { status: string; count: number }[];
  recentEvents: ExternalEventView[];
}

/** The integration account an external API key belongs to. */
export interface IntegrationAccountView {
  id: number | null;
  ref: string | null;
  name: string | null;
  email: string | null;
  userId: string | null;
  enabled: boolean;
}

/** One issued API key, without its secret (shown once at creation). */
export interface ApiKeyView {
  id: string;
  name: string | null;
  prefix: string | null;
  start: string | null;
  enabled: boolean;
  createdAt: string | null;
  expiresAt: string | null;
  lastRequest: string | null;
}

export interface IntegrationAccountStateView {
  account: IntegrationAccountView | null;
  apiKeys: ApiKeyView[];
  keysAvailable: boolean;
  configId: string | null;
}

export interface MeView {
  userId: string | null;
  name: string | null;
  email: string | null;
  roles: string[];
  role: string | null;
  memberId: number | null;
  memberGroupId: number | null;
}

/** One execution of a plan, as the Scheduler recorded it. */
export interface ScheduleOccurrenceView {
  id: string;
  status: string;
  reason: string | null;
  executionCount: number;
  startedAt: string | null;
  finishedAt: string | null;
  result: Record<string, unknown> | null;
}

/** One plan the Scheduler holds, with what its executions actually did. */
export interface ScheduleView {
  job: string;
  registered: boolean;
  scheduleId: string;
  title: string;
  cron: string;
  timezone: string;
  enabled: boolean;
  runCount: number;
  completedCount: number;
  nextRunAt: string | null;
  lastRunAt: string | null;
  occurrences: ScheduleOccurrenceView[];
}

export interface SchedulesView {
  jobs: ScheduleView[];
}

/** The receipt of asking one plan to run now. */
export interface ScheduledJobRunView {
  job: string;
  mode: 'scheduler' | 'direct';
  scheduleId: string;
  title: string;
  timezone: string;
  enabled: boolean;
  status: string;
  reason: string | null;
  result: Record<string, unknown> | null;
}
